import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./client/src/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // RamyPulse Obsidian Design System (from Stitch exports)
        "surface-container-lowest": "#0d0e10",
        "on-surface": "#e3e2e5",
        "on-background": "#e3e2e5",
        "surface-dim": "#121315",
        "on-secondary-container": "#b4b5b7",
        "on-surface-variant": "#e4beb1",
        "surface": "#121315",
        "surface-container-highest": "#343537",
        "inverse-on-surface": "#303033",
        "outline-variant": "#5b4137",
        "on-tertiary": "#003543",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "surface-container": "#1f2022",
        "outline": "#ab897d",
        "surface-container-low": "#1b1c1e",
        "primary-container": "#f56600",
        "on-secondary": "#2f3133",
        "tertiary-container": "#009fc3",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#1a1c1e",
        "on-tertiary-fixed-variant": "#004e60",
        "on-primary-fixed-variant": "#7a3000",
        "primary-fixed-dim": "#ffb693",
        "tertiary-fixed-dim": "#4cd6ff",
        "on-tertiary-fixed": "#001f28",
        "surface-variant": "#343537",
        "on-primary-container": "#4e1c00",
        "secondary-fixed": "#e2e2e5",
        "secondary-fixed-dim": "#c6c6c9",
        "on-primary": "#561f00",
        "secondary": "#c6c6c9",
        "tertiary": "#4cd6ff",
        "secondary-container": "#454749",
        "on-tertiary-container": "#00303c",
        "tertiary-fixed": "#b7eaff",
        "error-container": "#93000a",
        "primary-fixed": "#ffdbcc",
        "on-secondary-fixed-variant": "#454749",
        "surface-container-high": "#292a2c",
        "surface-bright": "#38393b",
        "background": "#121315",
        "inverse-surface": "#e3e2e5",
        "surface-tint": "#ffb693",
        "inverse-primary": "#a04100",
        "on-primary-fixed": "#351000",
        "primary": "#ffb693",
        // Shadcn token aliases (mapped to RamyPulse tokens)
        border: "#5b4137",
        input: "#343537",
        ring: "#ffb693",
        foreground: "#e3e2e5",
        muted: {
          DEFAULT: "#1f2022",
          foreground: "#b4b5b7",
        },
        accent: {
          DEFAULT: "#292a2c",
          foreground: "#e3e2e5",
        },
        popover: {
          DEFAULT: "#1f2022",
          foreground: "#e3e2e5",
        },
        card: {
          DEFAULT: "#1f2022",
          foreground: "#e3e2e5",
        },
        destructive: {
          DEFAULT: "#93000a",
          foreground: "#ffdad6",
        },
        secondary: {
          DEFAULT: "#454749",
          foreground: "#c6c6c9",
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.25rem",
        lg: "0.375rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"],
      },
      boxShadow: {
        "ambient": "0px 24px 24px 0px rgba(255,255,255,0.06)",
        "pulse-glow": "0 0 15px rgba(255,182,147,0.3)",
        "tertiary-glow": "0 0 8px rgba(76,214,255,0.4)",
        "error-glow": "0 0 8px rgba(255,180,171,0.4)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "pulse-custom": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.4" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "pulse-custom": "pulse-custom 2s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
