import type { Config } from "tailwindcss";

const token = (name: string) => `hsl(var(--${name}) / <alpha-value>)`;

export default {
  darkMode: ["class"],
  content: ["./client/src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": token("surface-container-lowest"),
        "on-surface": token("on-surface"),
        "on-background": token("on-background"),
        "surface-dim": token("surface-dim"),
        "on-secondary-container": token("on-secondary-container"),
        "on-surface-variant": token("on-surface-variant"),
        surface: token("surface"),
        "surface-container-highest": token("surface-container-highest"),
        "inverse-on-surface": token("inverse-on-surface"),
        "outline-variant": token("outline-variant"),
        "on-tertiary": token("on-tertiary"),
        error: token("error"),
        "on-error": token("on-error"),
        "surface-container": token("surface-container"),
        outline: token("outline"),
        "surface-container-low": token("surface-container-low"),
        "primary-container": token("primary-container"),
        "on-secondary": token("on-secondary"),
        "tertiary-container": token("tertiary-container"),
        "on-error-container": token("on-error-container"),
        "on-secondary-fixed": token("on-secondary-fixed"),
        "on-tertiary-fixed-variant": token("on-tertiary-fixed-variant"),
        "on-primary-fixed-variant": token("on-primary-fixed-variant"),
        "primary-fixed-dim": token("primary-fixed-dim"),
        "tertiary-fixed-dim": token("tertiary-fixed-dim"),
        "on-tertiary-fixed": token("on-tertiary-fixed"),
        "surface-variant": token("surface-variant"),
        "on-primary-container": token("on-primary-container"),
        "secondary-fixed": token("secondary-fixed"),
        "secondary-fixed-dim": token("secondary-fixed-dim"),
        "on-primary": token("on-primary"),
        tertiary: token("tertiary"),
        "secondary-container": token("secondary-container"),
        "on-tertiary-container": token("on-tertiary-container"),
        "tertiary-fixed": token("tertiary-fixed"),
        "error-container": token("error-container"),
        "primary-fixed": token("primary-fixed"),
        "on-secondary-fixed-variant": token("on-secondary-fixed-variant"),
        "surface-container-high": token("surface-container-high"),
        "surface-bright": token("surface-bright"),
        background: token("background"),
        "inverse-surface": token("inverse-surface"),
        "surface-tint": token("surface-tint"),
        "inverse-primary": token("inverse-primary"),
        "on-primary-fixed": token("on-primary-fixed"),
        primary: token("primary"),
        "primary-foreground": token("primary-foreground"),
        "primary-border": token("primary"),
        "secondary-foreground": token("secondary-foreground"),
        "secondary-border": token("outline-variant"),
        "destructive-foreground": token("destructive-foreground"),
        "destructive-border": token("destructive"),
        "accent-foreground": token("accent-foreground"),
        "popover-foreground": token("popover-foreground"),
        "card-foreground": token("card-foreground"),
        "card-border": token("outline-variant"),
        border: token("border"),
        input: token("input"),
        ring: token("ring"),
        foreground: token("foreground"),
        muted: {
          DEFAULT: token("muted"),
          foreground: token("muted-foreground"),
        },
        accent: {
          DEFAULT: token("accent"),
          foreground: token("accent-foreground"),
        },
        popover: {
          DEFAULT: token("popover"),
          foreground: token("popover-foreground"),
        },
        card: {
          DEFAULT: token("card"),
          foreground: token("card-foreground"),
        },
        destructive: {
          DEFAULT: token("destructive"),
          foreground: token("destructive-foreground"),
        },
        secondary: {
          DEFAULT: token("secondary"),
          foreground: token("secondary-foreground"),
        },
        success: token("signal-success"),
        warning: token("signal-warning"),
        info: token("signal-info"),
        monitor: token("monitor"),
        "monitor-container": token("monitor-container"),
        "on-monitor-container": token("on-monitor-container"),
        insight: token("insight"),
        "insight-container": token("insight-container"),
        "on-insight-container": token("on-insight-container"),
        action: token("action"),
        "action-container": token("action-container"),
        "on-action-container": token("on-action-container"),
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.375rem",
        md: "0.5rem",
        lg: "0.625rem",
        xl: "1rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Urbanist", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"],
      },
      boxShadow: {
        ambient: "0 18px 48px hsl(var(--shadow-color) / 0.09)",
        "pulse-glow": "0 10px 24px hsl(var(--primary) / 0.22)",
        "tertiary-glow": "0 4px 14px hsl(var(--tertiary) / 0.12)",
        "error-glow": "0 4px 14px hsl(var(--error) / 0.12)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "pulse-custom": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.4" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "pulse-custom": "pulse-custom 2s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
