import type {
  V3ActionItem,
  V3AnalyticsOverview,
  V3Case,
  V3MentionEvidence,
  V3Monitor,
  V3Notification,
  V3Observation,
  V3Report,
  V3Signal,
} from "@shared/v3";

export const V3_DEMO_MONITORS: V3Monitor[] = [
  {
    id: "mon_experience",
    organizationId: "demo-expo-2026",
    name: "Expérience client nationale",
    objective: "customer_experience",
    targetType: "organization",
    targetName: "LIDAL Démo",
    aliases: ["LIDAL", "LIDAL Algérie", "ليدال"],
    exclusions: ["recrutement", "emploi"],
    languages: ["fr", "ar", "darija", "arabizi"],
    territories: ["Alger", "Oran", "Constantine"],
    sources: ["facebook", "tiktok", "youtube", "google_maps"],
    competitors: [],
    frequencyMinutes: 360,
    maxMonthlyDocuments: 100_000,
    maxMonthlyCostDzd: 50_000,
    active: true,
    lastCollectedAt: "2026-08-17T18:12:00Z",
    coverageNote: "TikTok partiel · Google Maps collecté via un fournisseur pilote.",
  },
  {
    id: "mon_campaign",
    organizationId: "demo-expo-2026",
    name: "Campagne rentrée 2026",
    objective: "campaign",
    targetType: "campaign",
    targetName: "Rentrée 2026",
    aliases: ["rentrée LIDAL", "offre rentrée"],
    exclusions: [],
    languages: ["fr", "ar", "darija"],
    territories: ["Alger", "Oran"],
    sources: ["facebook", "youtube"],
    competitors: [],
    frequencyMinutes: 180,
    maxMonthlyDocuments: 25_000,
    maxMonthlyCostDzd: 20_000,
    active: true,
    lastCollectedAt: "2026-08-17T17:48:00Z",
    coverageNote: "Couverture des publications publiques uniquement.",
  },
];

export const V3_DEMO_MENTIONS: V3MentionEvidence[] = [
  {
    id: "m_1042",
    text: "internet y9ta3 bezaf w service client ma yjawbouch",
    source: "facebook",
    sourceUrl: "https://example.invalid/demo/facebook/m_1042",
    publishedAt: "2026-08-17T15:42:00Z",
    language: "darija_arabizi",
    territory: "Alger",
    sentiment: "negatif",
    aspects: ["connexion_reseau", "reactivite"],
    annotationStatus: "valid",
  },
  {
    id: "m_1047",
    text: "خدمة الزبائن ما تجاوبش والطلب بقى معلق ثلاثة أيام",
    source: "google_maps",
    sourceUrl: "https://example.invalid/demo/maps/m_1047",
    publishedAt: "2026-08-17T14:19:00Z",
    language: "darija_arabe",
    territory: "Oran",
    sentiment: "negatif",
    aspects: ["reactivite", "traitement_reclamation"],
    annotationStatus: "valid",
  },
  {
    id: "m_1051",
    text: "La nouvelle procédure est claire, j'ai reçu la confirmation rapidement.",
    source: "youtube",
    sourceUrl: "https://example.invalid/demo/youtube/m_1051",
    publishedAt: "2026-08-17T13:05:00Z",
    language: "francais",
    territory: "Constantine",
    sentiment: "positif",
    aspects: ["clarte_information", "reactivite"],
    annotationStatus: "valid",
  },
  {
    id: "m_1056",
    text: "Promesse intéressante mais les conditions ne sont pas expliquées dans la publication.",
    source: "tiktok",
    sourceUrl: "https://example.invalid/demo/tiktok/m_1056",
    publishedAt: "2026-08-17T12:28:00Z",
    language: "francais",
    territory: "Alger",
    sentiment: "mixte",
    aspects: ["transparence", "communication"],
    annotationStatus: "valid",
  },
];

export const V3_DEMO_OBSERVATIONS: V3Observation[] = [
  {
    id: "obs_reactivite",
    monitorId: "mon_experience",
    title: "Réponses du service client jugées trop lentes",
    summary: "Les verbatims récents associent les délais de réponse aux demandes non résolues.",
    mentionCount: 38,
    sentiment: "negatif",
    aspects: ["reactivite", "traitement_reclamation"],
    firstSeenAt: "2026-08-15T08:00:00Z",
    lastSeenAt: "2026-08-17T15:42:00Z",
    evidenceIds: ["m_1042", "m_1047"],
  },
  {
    id: "obs_clarte",
    monitorId: "mon_campaign",
    title: "La clarté de la procédure est appréciée",
    summary: "Les mentions positives citent la confirmation et la simplicité des étapes.",
    mentionCount: 31,
    sentiment: "positif",
    aspects: ["clarte_information", "reactivite"],
    firstSeenAt: "2026-08-12T09:00:00Z",
    lastSeenAt: "2026-08-17T13:05:00Z",
    evidenceIds: ["m_1051"],
  },
];

export const V3_DEMO_SIGNALS: V3Signal[] = [
  {
    id: "sig_negative_shift",
    monitorId: "mon_experience",
    title: "Bascule négative sur la réactivité du service client",
    summary: "Le taux négatif progresse de 18 points sur 74 mentions qualifiées.",
    severity: "high",
    status: "confirmed",
    signalType: "negative_shift",
    detectedAt: "2026-08-17T16:05:00Z",
    mentionCount: 74,
    velocityPercent: 32,
    confidence: 0.88,
    territory: "Alger · Oran",
    observationIds: ["obs_reactivite"],
    evidenceIds: ["m_1042", "m_1047"],
    explanation: "Seuil franchi : hausse de 18 points, supérieure au seuil de 15, avec 74 mentions.",
    priorityScore: 82,
    priorityFactors: [
      { label: "Gravité", value: 80, weight: 0.35 },
      { label: "Vitesse", value: 78, weight: 0.2 },
      { label: "Volume", value: 74, weight: 0.2 },
      { label: "Confiance", value: 88, weight: 0.25 },
    ],
  },
  {
    id: "sig_recurrence",
    monitorId: "mon_experience",
    title: "Réclamations récurrentes sur les demandes laissées en attente",
    summary: "Six mentions similaires ont été regroupées en moins de 24 heures.",
    severity: "medium",
    status: "investigating",
    signalType: "recurrence",
    detectedAt: "2026-08-17T14:34:00Z",
    mentionCount: 6,
    velocityPercent: null,
    confidence: 0.76,
    territory: "Oran",
    observationIds: ["obs_reactivite"],
    evidenceIds: ["m_1047"],
    explanation: "Seuil franchi : au moins 5 mentions similaires en 24 heures.",
    priorityScore: 58,
    priorityFactors: [
      { label: "Gravité", value: 55, weight: 0.4 },
      { label: "Volume", value: 42, weight: 0.25 },
      { label: "Confiance", value: 76, weight: 0.35 },
    ],
  },
  {
    id: "sig_campaign_clarity",
    monitorId: "mon_campaign",
    title: "Questions répétées sur les conditions de l’offre",
    summary: "Le thème transparence apparaît dans 16 commentaires de la campagne.",
    severity: "low",
    status: "new",
    signalType: "recurrence",
    detectedAt: "2026-08-17T12:45:00Z",
    mentionCount: 16,
    velocityPercent: 12,
    confidence: 0.71,
    territory: "Alger",
    observationIds: [],
    evidenceIds: ["m_1056"],
    explanation: "Seuil hebdomadaire franchi : 16 mentions similaires sur 7 jours.",
    priorityScore: 39,
    priorityFactors: [
      { label: "Gravité", value: 25, weight: 0.35 },
      { label: "Vitesse", value: 30, weight: 0.2 },
      { label: "Volume", value: 45, weight: 0.2 },
      { label: "Confiance", value: 71, weight: 0.25 },
    ],
  },
];

export const V3_DEMO_CASES: V3Case[] = [
  {
    id: "case_support",
    signalId: "sig_negative_shift",
    title: "Réduire le délai de réponse du support",
    status: "in_progress",
    priority: "high",
    ownerId: "u_nadia",
    ownerName: "Nadia B.",
    dueAt: "2026-08-20T17:00:00Z",
    expectedOutcome: "Identifier les deux causes principales et appliquer une correction testable.",
    openedAt: "2026-08-17T16:24:00Z",
    updatedAt: "2026-08-17T17:10:00Z",
    actionCount: 3,
    overdueActionCount: 1,
  },
];

export const V3_DEMO_ACTIONS: V3ActionItem[] = [
  {
    id: "act_audit",
    caseId: "case_support",
    title: "Auditer 20 conversations non résolues",
    description: "Classer les motifs de blocage et documenter les preuves dans le dossier.",
    status: "in_progress",
    ownerId: "u_nadia",
    ownerName: "Nadia B.",
    dueAt: "2026-08-18T12:00:00Z",
    expectedImpact: "Réduire les demandes sans réponse.",
    metricId: "median_time_to_ownership",
    baselineValue: 11.4,
    resultValue: null,
  },
  {
    id: "act_script",
    caseId: "case_support",
    title: "Tester un message d’accusé de réception",
    description: "Valider le texte avec le responsable support avant diffusion.",
    status: "open",
    ownerId: null,
    ownerName: null,
    dueAt: "2026-08-19T16:00:00Z",
    expectedImpact: "Donner une confirmation immédiate sans promettre un délai non garanti.",
    metricId: "negative_rate",
    baselineValue: 43.2,
    resultValue: null,
  },
];

export const V3_DEMO_OVERVIEW: V3AnalyticsOverview = {
  period: {
    start: "2026-07-19T00:00:00Z",
    end: "2026-08-17T23:59:59Z",
    comparisonStart: "2026-06-19T00:00:00Z",
    comparisonEnd: "2026-07-18T23:59:59Z",
  },
  qualifiedMentions: 428,
  collectedDocuments: 512,
  validAnnotations: 474,
  analyticalCoveragePercent: 92.6,
  netSentiment: 18.7,
  netSentimentDelta: -7.4,
  insufficientSample: false,
  distribution: { positif: 196, negatif: 116, neutre: 78, mixte: 38 },
  negativeRatePercent: 27.1,
  openSignalsBySeverity: { critical: 0, high: 1, medium: 1, low: 1 },
  medianTimeToOwnershipHours: 11.4,
  overdueActions: 1,
  topDrivers: [
    { aspect: "Réactivité", deltaPoints: -12.8, mentionCount: 91 },
    { aspect: "Clarté de l’information", deltaPoints: 6.4, mentionCount: 63 },
    { aspect: "Traitement des réclamations", deltaPoints: -5.9, mentionCount: 48 },
  ],
  sourceHealth: [
    { source: "facebook", status: "healthy", successRatePercent: 98, freshnessMinutes: 28, collectedDocuments: 184, analyticalCoveragePercent: 95 },
    { source: "tiktok", status: "degraded", successRatePercent: 81, freshnessMinutes: 96, collectedDocuments: 74, analyticalCoveragePercent: 87 },
    { source: "youtube", status: "healthy", successRatePercent: 100, freshnessMinutes: 42, collectedDocuments: 96, analyticalCoveragePercent: 94 },
    { source: "google_maps", status: "healthy", successRatePercent: 94, freshnessMinutes: 68, collectedDocuments: 158, analyticalCoveragePercent: 91 },
  ],
};

export const V3_DEMO_REPORTS: V3Report[] = [
  { id: "rpt_daily", title: "Brief du 17 août", reportType: "daily", periodStart: "2026-08-17T00:00:00Z", periodEnd: "2026-08-17T18:00:00Z", status: "ready", generatedAt: "2026-08-17T18:04:00Z", downloadUrl: null, evidenceCount: 83 },
  { id: "rpt_weekly", title: "Synthèse semaine 33", reportType: "weekly", periodStart: "2026-08-10T00:00:00Z", periodEnd: "2026-08-16T23:59:59Z", status: "ready", generatedAt: "2026-08-17T07:00:00Z", downloadUrl: null, evidenceCount: 312 },
];

export const V3_DEMO_NOTIFICATIONS: V3Notification[] = [
  { id: "notif_signal", title: "Signal confirmé", body: "La bascule négative a été transformée en dossier.", kind: "signal", read: false, createdAt: "2026-08-17T16:24:00Z", href: "/signals" },
  { id: "notif_due", title: "Action à échéance demain", body: "Auditer 20 conversations non résolues.", kind: "deadline", read: false, createdAt: "2026-08-17T17:15:00Z", href: "/actions" },
];
